version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  install-backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run: 
          name: Install Backend Dependencies
          command: npm run backend:install
  install-frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Using Yarn
          command: corepack enable
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install
  lint:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Lint Backend Project
          command: npm run backend:lint
      - run:
          name: Lint Frontend Project
          command: npm run frontend:lint
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Prepare dependencies
          command: 
            corepack enable
            npm run frontend:install
      # - run:
      #     name: Setup angular/cli
      #     command: 
      #       npm install -g @angular/cli@8.3.25
      #       npm install @angular-devkit/build-angular@0.803.24
      - run:
          name: Test Frontend Project
          command: npm run frontend:test
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Build Backend Project
          command: npm run backend:build
      - run:
          name: Build Frontend Project
          command: npm run frontend:build
  # deploy:
  #   docker:
  #     - image: "cimg/base:stable"
  #   steps:
  #     - node/install
  #     - checkout
  #     - run:
  #         name: Hello World
  #         command: echo 'Hello World'
workflows:
  udagram:
    jobs:
      - install-backend
      - install-frontend
      - test:
          requires:
            - install-frontend
      - build:
          requires:
            - test
#       - deploy