version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  install:
    - run: 
        name: Install Backend Dependencies
        command: npm run backend:install
    - run:
        name: Install Frontend Dependencies
        command: npm run frontend:install
  lint:
    - run:
        name: Lint Backend Project
        command: npm run backend:lint
    - run:
        name: Lint Frontend Project
        command: npm run frontend:lint
  test:
    - run:
        name: Test Backend Project
        command: npm run backend:test
    - run:
        name: Test Frontend Project
        command: npm run frontend:test
  build:
    docker:
      - image: "cimg/base:stable"
    - run:
        name: Build Backend Project
        command: npm run backend:build
    - run:
        name: Build Frontend Project
        command: npm run frontend:build
  deploy:
    - run:
        name: Hello World
        command: echo 'Hello World'
workflow:
  udagram:
    jobs:
      - install
      - lint
      - test
      - build
#       - deploy