version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  install:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - run:
          name: Using Yarn
          command: corepack enable
      - run: 
          name: Install Backend Dependencies
          command: npm run backend:install
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install
      - save_cache:
          key: udagram-cache
          paths:
            - udagram-api/node_modules
            - udagram-frontend/node_modules
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - restore_cache:
          key: udagram-cache
      - run:
          name: Build Backend Project
          command: npm run backend:build
      - run:
          name: Build Frontend Project
          command: npm run frontend:build
      - persist_to_workspace:
          root: /udagram
          paths:
            - udagram-api/www
            - udagram-frontend/www
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/install
      - eb/setup
      - checkout
      - attach_workspace:
          at: /udagram
      - run:
          name: Deploy Backend
          command: npm run backend:deploy
      - run:
          name: Deploy Frontend
          command: npm run frontend:deploy
workflows:
  udagram:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build