version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - run:
          name: Using Yarn
          command: corepack enable
      - run: 
          name: Install Backend Dependencies
          command: npm run backend:install
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install
      - run:
          name: Build Backend Project
          command: npm run backend:build
      - run:
          name: Build Frontend Project
          command: npm run frontend:build
  # deploy:
  #   docker:
  #     - image: "cimg/base:stable"
  #   steps:
  #     - node/install
  #     - checkout
  #     - run:
  #         name: Hello World
  #         command: echo 'Hello World'
workflows:
  udagram:
    jobs:
      - build
#       - deploy